version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter_notebook
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "8888:8888"

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "5005:5005"
    depends_on:
      - db

volumes:
  db_data: